# Generated by Django 6.1 on 2026-08-29 22:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012  # generated
        ("downloader", "0001_initial"),
    ]

    operations = [  # noqa: RUF012  # generated
        migrations.AddField(
            model_name="job",
            name="cancelled",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("running", "Running"),
                    ("done", "Done"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="queued",
                max_length=10,
            ),
        ),
    ]
